# Change the default shell and any required args
DefaultShell: sh -c

# Change the default start string to search for when inserting templates
InsertStart: START_PIN_HERE

#Change the default end string to search for when inserting templates
InsertEnd: END_PIN_HERE