version: 2
lint-debounce: 1s
document-formatting: true
tools:
  prettierd: &prettierd
    format-command: "prettierd ${INPUT}"
    format-stdin: true
    root-markers:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.js
      - .prettierrc.yml
      - .prettierrc.yaml
      - .prettierrc.json5
      - .prettierrc.mjs
      - .prettierrc.cjs
      - .prettierrc.toml
      - prettier.config.js
      - prettier.config.cjs
      - prettier.config.mjs

languages:
  css:
    - <<: *prettierd

  sass:
    - <<: *prettierd

  html:
    - <<: *prettierd

  json:
    - <<: *prettierd

  yaml:
    - <<: *prettierd

  javascript:
    - <<: *prettierd

  javascriptreact:
    - <<: *prettierd

  typescript:
    - <<: *prettierd

  typescriptreact:
    - <<: *prettierd

  [".svelte"]:
    - <<: *prettierd
    
  [".astro"]:
    - <<: *prettierd
