version: 2
lint-debounce: 1s
document-formatting: true
tools:
  prettierd: &prettierd
    format-command: "prettierd ${INPUT}"
    format-stdin: true

languages:
  css:
    - <<: *prettierd

  sass:
    - <<: *prettierd

  html:
    - <<: *prettierd

  json:
    - <<: *prettierd

  yaml:
    - <<: *prettierd

  javascript:
    - <<: *prettierd

  javascriptreact:
    - <<: *prettierd

  typescript:
    - <<: *prettierd

  typescriptreact:
    - <<: *prettierd
