# Commands go through bash
shell = "fish -c '{}'"

# Hyprland

[[items]]
file = "~/.config/hypr/colors.conf"
template = "hyprland"
rewrite = true
hook = "hyprctl reload"

# wezterm

[[item]]
file = "~/.config/wezterm/colors.lua"
template = "wezterm"
rewrite = true

# Zellij

[[item]]
file = "~/.config/zellij/themes/theme.kdl"
template = "zellij"
rewrite = true

# nnn

[[items]]
file = "~/.config/scripts/nnn/index.mjs"
template = "nnn"
start = "// Start flavours"
end = "// End flavours"
hook = "set -Ux NNN_FCOLORS (node ~/.config/scripts/nnn/index.mjs)"

# Helix

[[items]]
file = "~/.config/helix/themes/theme.toml"
template = "helix"
rewrite = true
hook = "pkill -USR1 hx"

# Wofi

[[item]]
file = "~/.config/wofi/style.css"
template = "wofi"
start = "/* Start flavours */"
end = "/* End flavours */"

# Waybar

[[item]]
file = "~/.config/waybar/colors.css"
template = "waybar"
rewrite = true
hook = "killall -SIGUSR2 waybar"

# Dunst

[[item]]
file = "~/.config/dunst/dunstrc"
template = "dunst"

# Swaylock

[[item]]
file = "~/.config/swaylock/config"
template = "swaylock"

# Wlogout - Uses same template format as waybar
[[item]]
file = "~/.config/wlogout/colors.css"
template = "waybar"
rewrite = true

# Firefox

[[item]]
file = "~/.config/cascade/chrome/includes/cascade-colours.css"
template = "cascade-firefox"
start = "/* Start flavours */"
end = "/* End flavours */"
hook = "killall firefox; hyprctl dispatch exec [workspace 4 silent] firefox"

# SVGs

[[item]]
file = "~/.config/waybar/circle.svg"
template = "svg"
subtemplate = "circle"
rewrite = true


[[item]]
file = "~/.config/wlogout/icons/suspend.svg"
template = "svg"
subtemplate = "suspend"
rewrite = true

[[item]]
file = "~/.config/wlogout/icons/shutdown.svg"
template = "svg"
subtemplate = "shutdown"
rewrite = true

[[item]]
file = "~/.config/wlogout/icons/hibernate.svg"
template = "svg"
subtemplate = "hibernate"
rewrite = true

[[item]]
file = "~/.config/wlogout/icons/lock.svg"
template = "svg"
subtemplate = "lock"
rewrite = true

[[item]]
file = "~/.config/wlogout/icons/logout.svg"
template = "svg"
subtemplate = "logout"
rewrite = true

[[item]]
file = "~/.config/wlogout/icons/reboot.svg"
template = "svg"
subtemplate = "reboot"
rewrite = true
