theme = "theme"

[editor]
line-number = "relative"
mouse = true
color-modes = true
bufferline = "always"

[keys.normal]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"
"C-u" = ["half_page_up", "goto_window_center"]
"C-d" = ["half_page_down", "goto_window_center"]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.indent-guides]
render = true
character = "┆"
skip-levels = 1

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
