#### Language servers

# Go
[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = [
  "golangci-lint",
  "run",
  "--enable-all",
  "--out-format",
  "json",
  "--issues-exit-code=1",
  "--allow-parallel-runners=true",
]

# Prettier
[language-server.efm-lsp-prettier]
command = "efm-langserver"
# required-root-patterns = [
#   ".prettierrc",
#   "prettierrc.json",
#   "prettierrc.js",
#   "prettierrc.yml",
#   "prettierrc.yaml",
#   "prettierrc.json5",
#   "prettierrc.mjs",
#   "prettierrc.cjs",
#   "prettierrc.toml",
# ]

[language-server.efm-lsp-prettier.config]
documentFormatting = true
languages = { typescript = [
  { formatCommand = "prettierd --stdin-filepath ${INPUT}", formatStdin = true },
], typescriptreact = [
  { formatCommand = "prettierd --stdin-filepath ${INPUT}", formatStdin = true },
], html = [
  { formatCommand = "prettierd --stdin-filepath ${INPUT}", formatStdin = true },
], css = [
  { formatCommand = "prettierd --stdin-filepath ${INPUT}", formatStdin = true },
], scss = [
  { formatCommand = "prettierd --stdin-filepath ${INPUT}", formatStdin = true },
], json = [
  { formatCommand = "prettierd --stdin-filepath ${INPUT}", formatStdin = true },
], markdown = [
  { formatCommand = "prettierd --stdin-filepath ${INPUT}", formatStdin = true },
] }

# ESLint 
[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]
# required-root-patterns = [
#   ".eslintrc.js",
#   ".eslintrc.cjs",
#   ".eslintrc.yaml",
#   ".eslintrc.yml",
#   ".eslintrc.json",
# ]

[language-server.eslint.config]
format = true
nodePath = ""
onIgnoredFiles = "off"
packageManager = "pnpm"
quiet = false
rulesCustomizations = []
run = "onType"
useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionOnSave = { mode = "all" }
experimental = {}
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }

# Astro 
[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { "typescript" = { "tsdk" = "/home/clara/.local/share/pnpm/global/5/node_modules/typescript/lib" }, "environment" = "node" }


#### Languages

[[language]]
name = "go"
language-servers = ["gopls", "golangci-lint-lsp"]
formatter = { command = "goimports" }
auto-format = true

[[language]]
name = "json"
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "efm-lsp-prettier",
]
auto-format = true

[[language]]
name = "html"
language-servers = [
  "vscode-html-language-server",
  "tailwindcss-ls",
  "efm-lsp-prettier",
]
auto-format = true

[[language]]
name = "css"
language-servers = [
  "vscode-css-language-server",
  "tailwindcss-ls",
  "efm-lsp-prettier",
]
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "efm-lsp-prettier",
  "eslint",
]
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "efm-lsp-prettier",
  "eslint",
]
auto-format = true

[[language]]
name = "jsx"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "efm-lsp-prettier",
  "eslint",
]
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "efm-lsp-prettier",
  "eslint",
]
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "markdown"
text-width = 80
soft-wrap = { wrap-at-text-width = true }
language-servers = ["marksman", "efm-lsp-prettier"]
auto-format = true

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
roots = ["package.json", "astro.config.mjs"]
language-servers = ["astro-ls"]
formatter = { command = 'prettier', args = ["--parser", "astro"] }
auto-format = true
