#### Language servers

# Efm
[language-server.efm-lsp]
command = "efm-langserver"

[language-server.efm-lsp.config]
documentFormatting = true
languages = { typescript = [
  { formatCommand = "prettierd --stdin-filepath ${INPUT}", formatStdin = true },
], typescriptreact = [
  { formatCommand = "prettierd --stdin-filepath ${INPUT}", formatStdin = true },
], html = [
  { formatCommand = "prettierd --stdin-filepath ${INPUT}", formatStdin = true },
], css = [
  { formatCommand = "prettierd --stdin-filepath ${INPUT}", formatStdin = true },
], scss = [
  { formatCommand = "prettierd --stdin-filepath ${INPUT}", formatStdin = true },
], json = [
  { formatCommand = "prettierd --stdin-filepath ${INPUT}", formatStdin = true },
], markdown = [
  { formatCommand = "prettierd --stdin-filepath ${INPUT}", formatStdin = true },
], go = [
  { lintCommand = "golangci-lint run", lintWorkspace = true },
] }

# ESLint 
[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]
required-root-patterns = [
  ".eslintrc.js",
  ".eslintrc.cjs",
  ".eslintrc.yaml",
  ".eslintrc.yml",
  ".eslintrc.json",
]

[language-server.eslint.config]
format = true
nodePath = ""
onIgnoredFiles = "off"
packageManager = "pnpm"
quiet = false
rulesCustomizations = []
run = "onType"
useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionOnSave = { mode = "all" }
experimental = {}
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }

# Astro 
[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { "typescript" = { "tsdk" = "/home/clara/.local/share/pnpm/global/5/node_modules/typescript/lib" }, "environment" = "node" }

# Emmet
[language-server.emmet-ls]
args = ["--stdio"]
command = "emmet-ls"

#### Languages

[[language]]
name = "go"
language-servers = ["gopls", "efm-lsp"]
formatter = { command = "goimports" }
auto-format = true

[[language]]
name = "json"
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "efm-lsp",
]
auto-format = true

[[language]]
name = "html"
language-servers = [
  "vscode-html-language-server",
  "emmet-ls",
  "tailwindcss-ls",
  "efm-lsp",
]
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls", "efm-lsp"]
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "efm-lsp",
  "eslint",
]
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "efm-lsp",
  "eslint",
]
auto-format = true

[[language]]
name = "jsx"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "emmet-ls",
  "efm-lsp",
  "eslint",
]
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "emmet-ls",
  "efm-lsp",
  "eslint",
]
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "markdown"
text-width = 80
soft-wrap = { wrap-at-text-width = true }
language-servers = ["marksman", "efm-lsp"]
auto-format = true

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
roots = ["package.json", "astro.config.mjs"]
language-servers = ["astro-ls", "emmet-ls"]
formatter = { command = 'prettier', args = ["--parser", "astro"] }
auto-format = true
