#### Language servers

# Astro 
[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { "typescript" = { "tsdk" = "/home/clara/.local/share/pnpm/global/5/node_modules/typescript/lib" }, "environment" = "node" }

# Emmet
[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

# Efm
[language-server.efm-lsp]
command = "efm-langserver"

# ESLint 
[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
format = true
nodePath = ""
onIgnoredFiles = "off"
packageManager = "pnpm"
quiet = false
rulesCustomizations = []
run = "onType"
useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionOnSave = { mode = "all" }
experimental = {}
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }

#### Languages

[[language]]
name = "sql"
formatter = { command = "sleek", args = ["--uppercase"] }
auto-format = true

[[language]]
name = "go"
formatter = { command = "goimports" }
auto-format = true

[[language]]
name = "json"
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "efm-lsp",
]
auto-format = true

[[language]]
name = "html"
language-servers = [
  { name = "vscode-html-language-server", except-features = [
    "format",
  ] },
  "emmet-lsp",
  "tailwindcss-ls",
  "efm-lsp",
]
auto-format = true

[[language]]
name = "css"
language-servers = [
  { name = "vscode-css-language-server", except-features = [
    "format",
  ] },
  "tailwindcss-ls",
  "efm-lsp",
]
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "efm-lsp",
  "eslint",
]
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "efm-lsp",
  "eslint",
]
auto-format = true

[[language]]
name = "jsx"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "emmet-lsp",
  "efm-lsp",
  "eslint",
]
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "emmet-lsp",
  "efm-lsp",
  "eslint",
]
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "yaml"
language-servers = ["efm-lsp"]
auto-format = true

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
roots = ["package.json", "astro.config.mjs"]
language-servers = ["astro-ls", "emmet-lsp", "efm-lsp"]
auto-format = true

[[language]]
name = "svelte"
scope = "source.svelte"
injection-regex = "svelte"
file-types = ["svelte"]
indent = { tab-width = 2, unit = "  " }
language-servers = ["svelteserver", "emmet-lsp", "efm-lsp", "eslint"]
auto-format = true
